


<div class="footer-container">
	<footer>
		TAX ID#: 11-3812766 A COPY OF THE OFFICIAL REGISTRATION AND FINANCIAL INFORMATION MAY BE OBTAINED FROM THE DIVISION OF CONSUMER SERVICES BY CALLING TOLL-FREE (800-435-7352) WITHIN THE STATE. REGISTRATION DOES NOT IMPLY ENDORSEMENT, APPROVAL, OR RECOMMENDATION BY THE STATE. FLORIDA SOLICITATION REGISTRATION #CH25850

	</footer>
</div>

<?php wp_footer(); ?>

	</body>
</html>
